main:
  - name: Home
    URL: /
    weight: 1
  - name: Team
    URL: team
    weight: 2
  - name: Helfende
    URL: registration
    weight: 3
  - name: Tom dä Bom
    URL: tomdaebom
    weight: 4
  - name: Infos
    hasChildren: true
    weight: 5
  - name: Häufige Fragen
    parent: Infos
    URL: faq
    weight: 1
  - name: Packliste
    parent: Infos
    URL: packliste
    weight: 2
  - name: Jugendurlaub
    parent: Infos
    URL: jugendurlaub
    weight: 3
  - name: Spenden
    URL: spenden
    weight: 6

footer:
  - name: 
    URL: 
    weight: 1
